services:
  angular-builder:
    build:
      context: .
      dockerfile: Dockerfile
      target: output
    volumes:
      - C:\dev\Programs\nginx\html:/usr/share/nginx/html
    command:  >
      sh -c "
      echo 'Copying Angular build files to nginx directory...' &&
      cp -r /usr/share/nginx/html/* /usr/share/nginx/html/ &&
      echo 'Files copied successfully!'
      "